steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'asia-northeast1-docker.pkg.dev/$PROJECT_ID/writing-assistant/my-app', '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/writing-assistant/my-app'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'my-app',
      '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/writing-assistant/my-app',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/writing-assistant/my-app'

options:
  # Cloud Buildのビルドログ保存方法を明示する
  # デフォルトではGoogle が作成したデフォルト バケットへビルドログが保存される
  # とくに分析用途などでは使用していないため、CLOUD_LOGGING_ONLYに変更する
  # https://cloud.google.com/build/docs/securing-builds/store-manage-build-logs?hl=ja
  logging: CLOUD_LOGGING_ONLY
