steps:
  # Dockerコンテナのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'asia-northeast1-docker.pkg.dev/$PROJECT_ID/writing-assistant/my-app', '.'
    ]

  # Dockerコンテナのpush
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/writing-assistant/my-app'
    ]

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'my-app',
      '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/writing-assistant/my-app',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--update-secrets', 'SLACK_BOT_TOKEN=slack-api-token:latest,SLACK_BOT_URL=slack-bot-url:latest,DIFY_API_URL=dify-api-url:latest,BASIC_DIFY_API_KEY=basic-dify-api-key:latest,GENERATE_OUTLINE_DIFY_API_KEY=generate-outline-dify-api-key:latest,GENERATE_ARTICLE_DIFY_API_KEY=generate-article-dify-api-key:latest'
    ]

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/writing-assistant/my-app'

options:
  logging: CLOUD_LOGGING_ONLY
